import { FormEvent, useState } from 'react';
import { request } from '../../api';
import type { CombinationResponse, FunctionTag } from '../../types';

export function CombinationPanel({ functionTags, onOpenSpecies }: { functionTags: FunctionTag[]; onOpenSpecies: (slug: string) => void }) {
  const [firstTag, setFirstTag] = useState(''); const [secondTag, setSecondTag] = useState(''); const [loading, setLoading] = useState(false); const [result, setResult] = useState<CombinationResponse | null>(null); const [error, setError] = useState(''); const [feedback, setFeedback] = useState('');
  async function submit(event: FormEvent) { event.preventDefault(); setLoading(true); setError(''); setFeedback(''); try { setResult(await request<CombinationResponse>('/api/recommendations/combinations', { method: 'POST', body: JSON.stringify({ functionTags: [firstTag, secondTag], safetyLevel: 'BSL-1' }) })); } catch (cause) { setError(cause instanceof Error ? cause.message : '组合推荐失败'); } finally { setLoading(false); } }
  async function sendFeedback(feedbackType: 'helpful'|'unhelpful') { if (!result) return; const content = window.prompt(feedbackType === 'helpful' ? '这个组合哪里有帮助？（可选）' : '这个组合有什么问题？（可选）') ?? ''; try { await request(`/api/recommendations/combinations/${result.recordId}/feedback`, { method: 'POST', body: JSON.stringify({ feedbackType, content }) }); setFeedback(feedbackType); } catch (cause) { setError(cause instanceof Error ? cause.message : '反馈失败'); } }
  const range = (min?: number, max?: number, unit = '') => min == null || max == null ? '未知' : `${min}–${max}${unit}`;
  return <section className="combinationPanel"><div><p className="eyebrow">Consortium Design</p><h2>组合菌建议</h2><p>选择两个目标功能，检查候选菌的功能互补性和培养区间交集。</p></div><form onSubmit={submit}><select aria-label="第一个目标功能" required value={firstTag} onChange={(event) => setFirstTag(event.target.value)}><option value="">选择功能一</option>{functionTags.map((tag) => <option key={tag.id} value={tag.code}>{tag.name}</option>)}</select><select aria-label="第二个目标功能" required value={secondTag} onChange={(event) => setSecondTag(event.target.value)}><option value="">选择功能二</option>{functionTags.map((tag) => <option key={tag.id} value={tag.code} disabled={tag.code === firstTag}>{tag.name}</option>)}</select><button disabled={loading || !firstTag || !secondTag}>{loading ? '计算中…' : '生成组合建议'}</button></form>{error && <div className="message error">{error}</div>}{result && <div className="combinationResults">{result.items.map((item, index) => <article key={index}><div className="combinationTitle"><strong>组合评分 {item.score}</strong><span className={item.compatible ? 'compatible' : 'reviewRequired'}>{item.compatible ? '存在共同培养窗口' : '需实验优化'}</span></div><div className="combinationMembers">{item.members.map((member) => <button key={member.id} onClick={() => onOpenSpecies(member.slug)}><strong>{member.latinName}</strong><small>{member.functionTags.join('、')} · {member.evidenceCount} 条证据</small></button>)}</div><p>共同温度：{range(item.temperatureMin, item.temperatureMax, ' °C')} · 共同 pH：{range(item.phMin, item.phMax)}</p><ul>{item.reasons.map((reason) => <li key={reason}>{reason}</li>)}</ul>{item.warning && <div className="riskWarning">{item.warning}</div>}</article>)}{!result.items.length && <div className="empty">暂无满足两个功能且菌种不重复的组合。</div>}<p className="disclaimer">{result.disclaimer}</p><div className="combinationFeedback">{feedback ? <span>感谢反馈，已纳入组合质量分析。</span> : <><span>这个组合建议有帮助吗？</span><button onClick={() => void sendFeedback('helpful')}>👍 有帮助</button><button onClick={() => void sendFeedback('unhelpful')}>👎 无帮助</button></>}</div></div>}</section>;
}
