import { useEffect, useState } from 'react';
import { request } from '../../api';
import { PageHeader } from '../../components/Common';
import type { DataQualityOverview, RecommendationQuality, SearchReport } from '../../types';
import { CombinationExperimentForm } from './CombinationExperimentForm';

export function DataQualityPage() {
  const [report, setReport] = useState<DataQualityOverview | null>(null); const [error, setError] = useState('');
  async function load() { try { setReport(await request<DataQualityOverview>('/api/admin/data-quality')); } catch (cause) { setError(cause instanceof Error ? cause.message : '数据质量加载失败'); } }
  useEffect(() => { void load(); }, []);
  return <section className="content"><PageHeader title="数据质量" description="查看整体完整度、高频缺失项和优先补全菌种。" action={<button className="primary" onClick={() => void load()}>刷新</button>} />{error && <div className="message error">{error}</div>}{report ? <><section className="analyticsStats qualityStats"><article><strong>{report.averageScore.toFixed(1)}</strong><span>平均质量分</span></article><article><strong>{report.complete}</strong><span>完整（≥80）</span></article><article><strong>{report.needsCompletion}</strong><span>待补充（60–79）</span></article><article><strong>{report.incomplete}</strong><span>不完整（&lt;60）</span></article></section><section className="analyticsGrid"><div className="panel"><div className="panelTitle"><h3>高频缺失项</h3><span>{report.total} 个未归档菌种</span></div>{report.missing.map((item) => <div className={`queryRow ${item.count ? 'warning' : ''}`} key={item.key}><strong>{item.label}</strong><span>{item.count} 个缺失</span></div>)}</div><div className="panel"><div className="panelTitle"><h3>优先补全列表</h3></div>{report.prioritySpecies.map((item) => <div className="queryRow" key={item.id}><div><strong>{item.latinName}</strong><small>{item.slug} · {item.status}</small></div><span>{item.score} 分</span></div>)}{!report.prioritySpecies.length && <div className="empty">暂无待补全菌种。</div>}</div></section></> : <div className="panel placeholderPanel">质量数据加载中…</div>}</section>;
}

export function SearchAnalytics() {
  const [days, setDays] = useState(30); const [report, setReport] = useState<SearchReport | null>(null); const [error, setError] = useState('');
  async function load(nextDays = days) { try { setReport(await request<SearchReport>(`/api/admin/search-analytics?days=${nextDays}`)); } catch (cause) { setError(cause instanceof Error ? cause.message : '搜索分析加载失败'); } }
  useEffect(() => { void load(); }, []);
  return <section className="content"><PageHeader title="搜索分析" description="查看用户真实搜索需求和无结果查询，为数据补充与同义词建设提供依据。" action={<select value={days} onChange={(event) => { const value = Number(event.target.value); setDays(value); void load(value); }}><option value="7">最近 7 天</option><option value="30">最近 30 天</option><option value="90">最近 90 天</option></select>} />{error && <div className="message error">{error}</div>}{report ? <><section className="analyticsStats"><article><strong>{report.totalSearches}</strong><span>搜索次数</span></article><article><strong>{report.distinctQueries}</strong><span>不同关键词</span></article><article><strong>{report.noResultSearches}</strong><span>无结果搜索</span></article></section><section className="analyticsGrid"><div className="panel"><div className="panelTitle"><h3>热门关键词</h3></div>{report.popularQueries.map((item) => <div className="queryRow" key={item.query}><strong>{item.query}</strong><span>{item.count} 次 · 平均 {item.averageResults.toFixed(1)} 条</span></div>)}{!report.popularQueries.length && <div className="empty">暂无关键词搜索记录。</div>}</div><div className="panel"><div className="panelTitle"><h3>无结果关键词</h3></div>{report.noResultQueries.map((item) => <div className="queryRow warning" key={item.query}><strong>{item.query}</strong><span>{item.count} 次</span></div>)}{!report.noResultQueries.length && <div className="empty">暂无无结果关键词。</div>}</div></section></> : <div className="panel placeholderPanel">分析数据加载中…</div>}</section>;
}

export function RecommendationQualityPage() {
  const [report, setReport] = useState<RecommendationQuality | null>(null); const [error, setError] = useState('');
  async function load() { try { setReport(await request<RecommendationQuality>('/api/admin/recommendations')); } catch (cause) { setError(cause instanceof Error ? cause.message : '推荐质量加载失败'); } }
  useEffect(() => { void load(); }, []);
  const feedbackTotal = (report?.helpful ?? 0) + (report?.unhelpful ?? 0); const helpfulRate = feedbackTotal ? Math.round((report!.helpful / feedbackTotal) * 100) : 0;
  return <section className="content"><PageHeader title="推荐质量" description="跟踪单菌和组合菌推荐结果、风险等级、用户反馈与实验验证。" action={<button className="primary" onClick={() => void load()}>刷新</button>} />{error && <div className="message error">{error}</div>}{report ? <><section className="analyticsStats"><article><strong>{report.total}</strong><span>单菌推荐</span></article><article><strong>{report.combinations?.length ?? 0}</strong><span>组合设计记录</span></article><article><strong>{helpfulRate}%</strong><span>单菌有帮助率</span></article></section><div className="panel recommendationAuditList"><div className="panelTitle"><h3>单菌推荐记录</h3></div>{report.records.map((record) => <article key={record.id}><div className="qualityHeader"><div><strong>{record.requirement}</strong><small>{new Date(record.createdAt).toLocaleString()} · {record.modelName}</small></div><span className={record.riskLevel === 'low' ? 'countSuccess' : 'countWarning'}>{record.riskLevel}</span></div><div className="candidateSummary">{record.items.map((item) => <span key={item.latinName}>{item.latinName} · {item.score} 分</span>)}</div><div className="qualityFeedback">👍 {record.helpfulCount}　👎 {record.unhelpfulCount}</div></article>)}{!report.records.length && <div className="empty">暂无单菌推荐记录。</div>}</div><div className="panel recommendationAuditList combinationAudit"><div className="panelTitle"><h3>组合菌设计记录</h3></div>{report.combinations?.map((record) => <article key={record.id}><div className="qualityHeader"><div><strong>{record.functionTags.join(' + ')}</strong><small>{new Date(record.createdAt).toLocaleString()} · {record.modelName}</small></div><span className={record.riskLevel === 'low' ? 'countSuccess' : 'countWarning'}>{record.riskLevel}</span></div><div className="candidateSummary">{record.items.map((item, index) => <span key={index}>#{index + 1} {item.members.map((member) => member.latinName).join(' + ')} · {item.score} 分 · {item.compatible ? '兼容' : '待验证'}</span>)}</div><div className="qualityFeedback">👍 {record.helpfulCount}　👎 {record.unhelpfulCount}</div><div className="experimentHistory"><strong>实验历史（{record.experiments?.length ?? 0}）</strong>{record.experiments?.map((experiment) => <div key={experiment.id}><span>#{experiment.candidateIndex + 1} {experiment.candidateMembers?.map((member) => member.latinName).join(' + ')} · {experiment.outcome === 'compatible' ? '兼容' : experiment.outcome === 'incompatible' ? '不兼容' : '结论不明确'}</span><small>{experiment.temperature != null ? `${experiment.temperature} °C` : '温度未记录'} · {experiment.ph != null ? `pH ${experiment.ph}` : 'pH 未记录'} · {new Date(experiment.createdAt).toLocaleString()}</small>{experiment.notes && <p>{experiment.notes}</p>}</div>)}</div><CombinationExperimentForm recordId={record.id} candidates={record.items} onSaved={() => void load()} /></article>)}{!report.combinations?.length && <div className="empty">暂无组合菌设计记录。</div>}</div></> : <div className="panel placeholderPanel">推荐质量加载中…</div>}</section>;
}
