import { fireEvent, render, screen, waitFor } from '@testing-library/react';
import { describe, expect, it, vi } from 'vitest';
import { AccountPanel } from './AccountPanel';

const species={id:'s1',slug:'bacillus',latinName:'Bacillus',chineseName:'芽孢杆菌',strainNumber:'',sourceEnvironment:'',safetyLevel:'BSL-1',isModelOrganism:false,summary:'',status:'published' as const,dataQualityScore:90,createdAt:'',updatedAt:''};
const base={selected:null,favorites:[],history:[],onLogout:vi.fn(),onToggleFavorite:vi.fn(),onRunHistory:vi.fn(),onClearHistory:vi.fn(),onOpenSpecies:vi.fn()};

describe('AccountPanel',()=>{
  it('登录和注册用户',async()=>{const onLogin=vi.fn().mockResolvedValue(undefined);const onRegister=vi.fn().mockResolvedValue(undefined);render(<AccountPanel {...base} user={null} onLogin={onLogin} onRegister={onRegister}/>);fireEvent.change(screen.getByLabelText('用户邮箱'),{target:{value:'user@example.com'}});fireEvent.change(screen.getByLabelText('用户密码'),{target:{value:'password1'}});fireEvent.click(screen.getByRole('button',{name:'登录'}));await waitFor(()=>expect(onLogin).toHaveBeenCalledWith('user@example.com','password1'));fireEvent.click(screen.getByRole('button',{name:'创建账号'}));fireEvent.change(screen.getByLabelText('显示名称'),{target:{value:'研究员'}});fireEvent.click(screen.getByRole('button',{name:'注册'}));await waitFor(()=>expect(onRegister).toHaveBeenCalledWith('研究员','user@example.com','password1'))});
  it('操作收藏与搜索历史',()=>{const onToggleFavorite=vi.fn(),onRunHistory=vi.fn(),onOpenSpecies=vi.fn(),onClearHistory=vi.fn();const history={id:'h1',query:'生防菌',filters:{functionTag:'biocontrol'},resultCount:2,createdAt:'2026-01-01'};render(<AccountPanel {...base} user={{id:'u1',email:'u@example.com',displayName:'用户',role:'member'}} selected={species} favorites={[species]} history={[history]} onLogin={vi.fn()} onRegister={vi.fn()} onToggleFavorite={onToggleFavorite} onRunHistory={onRunHistory} onOpenSpecies={onOpenSpecies} onClearHistory={onClearHistory}/>);fireEvent.click(screen.getByRole('button',{name:'取消收藏当前菌种'}));expect(onToggleFavorite).toHaveBeenCalledWith(species);fireEvent.click(screen.getByRole('button',{name:/Bacillus/}));expect(onOpenSpecies).toHaveBeenCalledWith('bacillus');fireEvent.click(screen.getByRole('button',{name:/生防菌/}));expect(onRunHistory).toHaveBeenCalledWith(history);fireEvent.click(screen.getByRole('button',{name:'清空'}));expect(onClearHistory).toHaveBeenCalled()});
});
