import { FormEvent, useEffect, useState } from 'react';
import { request } from '../../api';
import { Messages, PageHeader } from '../../components/Common';
import type { ListResponse, SearchRecallRule, SearchSynonym } from '../../types';

export function SearchConfigManagement() {
  const [synonyms,setSynonyms]=useState<SearchSynonym[]>([]); const [rules,setRules]=useState<SearchRecallRule[]>([]); const [error,setError]=useState(''); const [notice,setNotice]=useState('');
  const [synonym,setSynonym]=useState({term:'',synonym:'',weight:.85,enabled:true}); const [rule,setRule]=useState({name:'',queryPattern:'',functionTagCode:'',safetyLevel:'',boost:.15,enabled:true});
  async function load(){try{const [a,b]=await Promise.all([request<ListResponse<SearchSynonym>>('/api/admin/search-config/synonyms'),request<ListResponse<SearchRecallRule>>('/api/admin/search-config/rules')]);setSynonyms(a.items);setRules(b.items)}catch(e){setError(e instanceof Error?e.message:'搜索配置加载失败')}}
  useEffect(()=>{void load()},[]);
  async function addSynonym(e:FormEvent){e.preventDefault();try{await request('/api/admin/search-config/synonyms',{method:'POST',body:JSON.stringify(synonym)});setSynonym({term:'',synonym:'',weight:.85,enabled:true});setNotice('同义词已新增');await load()}catch(x){setError(x instanceof Error?x.message:'保存失败')}}
  async function addRule(e:FormEvent){e.preventDefault();try{await request('/api/admin/search-config/rules',{method:'POST',body:JSON.stringify(rule)});setRule({name:'',queryPattern:'',functionTagCode:'',safetyLevel:'',boost:.15,enabled:true});setNotice('召回规则已新增');await load()}catch(x){setError(x instanceof Error?x.message:'保存失败')}}
  async function remove(kind:'synonyms'|'rules',id:string){if(!window.confirm('确认删除该搜索配置？'))return;try{await request(`/api/admin/search-config/${kind}/${id}`,{method:'DELETE'});setNotice('搜索配置已删除');await load()}catch(x){setError(x instanceof Error?x.message:'删除失败')}}
  async function reindex(){try{const data=await request<{indexed:number}>('/api/admin/search-config/reindex',{method:'POST',body:'{}'});setNotice(`向量索引已更新：${data.indexed} 个菌种`)}catch(x){setError(x instanceof Error?x.message:'向量索引更新失败')}}
  return <section className="content"><PageHeader title="智能搜索配置" description="维护语义检索同义词、业务召回规则并重建菌种向量索引。" action={<button className="primary" onClick={()=>void reindex()}>重建向量索引</button>}/><Messages error={error} notice={notice}/><section className="mainGrid"><div className="panel tablePanel"><div className="panelTitle"><h3>同义词</h3><span>{synonyms.length} 条</span></div>{synonyms.map(x=><div className="queryRow" key={x.id}><div><strong>{x.term} → {x.synonym}</strong><small>权重 {x.weight} · {x.enabled?'启用':'停用'}</small></div><button className="danger" onClick={()=>void remove('synonyms',x.id)}>删除</button></div>)}<form className="inlineConfigForm" onSubmit={addSynonym}><input aria-label="标准词" required placeholder="标准词" value={synonym.term} onChange={e=>setSynonym({...synonym,term:e.target.value})}/><input aria-label="同义表达" required placeholder="同义表达" value={synonym.synonym} onChange={e=>setSynonym({...synonym,synonym:e.target.value})}/><button>新增</button></form></div>
    <div className="panel tablePanel"><div className="panelTitle"><h3>召回规则</h3><span>{rules.length} 条</span></div>{rules.map(x=><div className="queryRow" key={x.id}><div><strong>{x.name}</strong><small>命中“{x.queryPattern}” · 功能 {x.functionTagCode||'不限'} · 加权 {x.boost}</small></div><button className="danger" onClick={()=>void remove('rules',x.id)}>删除</button></div>)}<form className="inlineConfigForm" onSubmit={addRule}><input aria-label="规则名称" required placeholder="规则名称" value={rule.name} onChange={e=>setRule({...rule,name:e.target.value})}/><input aria-label="查询模式" required placeholder="查询包含词" value={rule.queryPattern} onChange={e=>setRule({...rule,queryPattern:e.target.value})}/><input aria-label="功能标签编码" placeholder="功能标签编码" value={rule.functionTagCode} onChange={e=>setRule({...rule,functionTagCode:e.target.value})}/><button>新增</button></form></div></section></section>
}
